# Generated by Django 2.1.3 on 2019-02-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(max_length=20)),
                ('pos', models.CharField(max_length=20)),
                ('rsid', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=30)),
                ('who', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='blacks',
            name='ver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blacklist.Version'),
        ),
    ]
