# Generated by Django 2.0.9 on 2019-02-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacks',
            name='rsid',
            field=models.CharField(max_length=50),
        ),
    ]
