# Generated by Django 2.1.3 on 2019-02-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_auto_20190206_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
