# Generated by Django 2.1.3 on 2019-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0004_auto_20190207_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacks',
            name='rsid',
            field=models.CharField(max_length=50),
        ),
    ]
