# Generated by Django 2.0.9 on 2019-01-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_num', models.CharField(max_length=20)),
                ('box_num', models.CharField(max_length=30)),
                ('barcode_num', models.CharField(max_length=30)),
                ('well_num', models.CharField(max_length=10)),
                ('freezer_num', models.CharField(max_length=20)),
            ],
        ),
    ]
